Enable gradle enterprise
apollographql/apollo-kotlin pull request #4848
Opened 2023-04-06 15:27 UTC by martinbonnin

Enable ge.apollographql.com.

You'll have to run  `./gradlew provisionGradleEnterpriseAccessKey` to upload builds.

2023-04-06 15:29 UTC, BoD approved these changes
🚀

2023-04-07 17:59 UTC, etiennestuder requested changes

2023-04-07 17:59 UTC, etiennestuder commented on settings.gradle.kts
> +  allowUntrustedServer = true
This should be set to `false`.

2023-04-08 04:18 UTC, etiennestuder approved these changes
LGTM

2023-04-11 07:22 UTC, merged